### ISSUE TITLE
Am not able to implement your flutter demo project ,am facing issues with that

### ISSUE THREAD

**Issue by swathieventhq** [cometchat-pro/cometchat-pro-flutter-ui-kit#4]
Describe the problem

Error: Too many positional arguments: 0 allowed, but 3 found.
Try removing the extra positional arguments.
      CometChat.createGroup(gUid, _groupName, _groupType,

 What was the expected behavior?

 i just wanted to implement the cometchat in my  flutter application

Reproduction

 I cloned your demo flutter project and tried to implement it, but am getting the above error 

Environment

> Please provide the following:

- Version used: cometchat: ^3.0.5
![Screenshot 2023-01-20 at 4 56 06 PM](https://user-images.githubusercontent.com/121167388/213684807-ad280105-5f59-42bb-b78d-d38753b4b327.png)
![Screenshot 2023-01-20 at 4 56 58 PM](https://user-images.githubusercontent.com/121167388/213684831-e21100a5-4d2a-497f-bd72-b7eaee2ee9a7.png)

**Comment by swathieventhq** [comment]
i just wanted to implement the cometchat in my flutter application.  I went through your documentation and I cloned your demo flutter project 2 days ago and tried to implement it, but am getting thefollowing error.

Error: Too many positional arguments: 0 allowed, but 3 found.
Try removing the extra positional arguments.
CometChat.createGroup(gUid, _groupName, _groupType,

**Comment by PeterOcansey** [comment]
Facing same issue with integrating flutter ui kit into our app. I can't even build the app after integration. cc @Shantanu-CometChat 

<img width="915" alt="Screenshot 2023-01-29 at 1 11 14 PM" src="https://user-images.githubusercontent.com/52463144/215328658-4399459e-298c-45eb-963f-b41b4b88e0d5.png">
